const express = require('express');
const { register, login, forgotPassword, verifyOtp, logout, recoveryEmail, createPassword } = require('../controllers/userController');
const router = express.Router();
router.post('/auth/sign-up', register);
router.post('/auth/login', login);
router.post('/auth/forgot', forgotPassword);
router.post('/auth/verify-otp', verifyOtp);
router.post('/auth/logout', logout);
router.post('/auth/create-password', createPassword);
router.post('/auth/reset-password/:id');
router.post('/auth/recovery-email', recoveryEmail);
module.exports = router;